### ISSUE TITLE
2 cameraView in one Activty

### ISSUE THREAD

**Issue by makbn** [protyposis/Spectaculum#4]
hi, I want to have 2 camera view just in one activity one for the left eye and another for the right!
but just one of them shows the camera preview! do you have any idea how can I implement what I want?

here is my code:
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        setContentView(R.layout.activity_cameraview);
        super.onCreate(savedInstanceState);
        mCameraView = (CameraView) findViewById(R.id.spectaculum);
        mCameraView2 = (CameraView) findViewById(R.id.spectaculum2);

        initCamera(mCameraView);
        initCamera(mCameraView2);

    }

void initCamera(CameraView  mCameraView){

        mCameraView.setOnFrameCapturedCallback(new Utils.OnFrameCapturedCallback(this, "spectaculum-camera"));
        mCameraView.setTouchEnabled(true); // enable zoom&pan
    }
```

**Comment by protyposis** [comment]
This does not work because the Android Camera API does not allow multiple previews at the same time, so there can only be one `CameraView` at a time. To duplicate the preview for two eyes you can write a simple `ShaderEffect` that renders the preview twice, side by side.

**Comment by makbn** [comment]
can you add more details, please? you mean I can copy view of `mCameraView` by `ShaderEffect` ?

**Comment by protyposis** [comment]
Please make yourself familiar with shaders and take a look at `FlipEffect` to understand how effects in Spectaculum work. You'll then see that you basically get the camera image as input into the shader, and you can output and transform it however you want. In your case, you'd scale and/or crop the input camera image texture and render it twice into the output texture.

**Comment by makbn** [comment]
thank you! and one more question is how can I make SpectaculumView full screen?I choose match parent in XML but 30% of the screen is white! sorry for the irrelevant question to this topic!
