### ISSUE TITLE
How to record a video in android

### ISSUE THREAD

**Issue by SumitMarwha** [protyposis/Spectaculum#5]
I am using SpectaculumView to preview camera. I want to record video instead of capturing frame. How can i do it

**Comment by protyposis** [comment]
Recording a video is not related to Spectaculum, so I'm closing this. Spectaculum is just a view for picture data and recording is not one of its concerns.

You should take a look into `MediaRecorder` and `MediaCodec`. I'm sure there's libraries out there that make it easy to record video from the camera as well.
